name: github pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
          
      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
          
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        # run: dotnet publish HomeWasm/HomeWasm.Client/HomeWasm.Client.csproj -c:Release -p:GHPages=true -o dist/Web --nologo
        run: dotnet publish HomeWasm.sln -c:Release -p:GHPages=true -o dist/Web --nologo

      # changes the base-tag in index.html from '/' to 'WebPortfolio' to match GitHub Pages repository subdirectory
      #- name: Change base-tag in index.html from / to WebPortfolio
      #  run: sed -i 's/<base href="\/" \/>/<base href="\/WebPortfolio\/" \/>/g' dist/Web/wwwroot/index.html

      #Publish static files to Github pages
      # token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/Web/wwwroot
